#!/usr/bin/env python3
"""Rebuild the 30×10 kids curriculum (v2) and words.json."""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data" / "image_plan_300.csv"
WORDS_PATH = ROOT / "data" / "words.json"
APP_WORDS = ROOT / "app" / "EnglishWordKids" / "Resources" / "words.json"
NOTES = ROOT / "data" / "CURRICULUM_V2_NOTES.md"

# day -> (theme, [10 words])
DAYS: list[tuple[str, list[str]]] = [
    ("Daily routine", [
        "wake up", "get up", "wash", "brush teeth", "get dressed",
        "breakfast", "go to school", "homework", "play", "sleep",
    ]),
    ("Family", [
        "family", "mother", "father", "brother", "sister",
        "grandma", "grandpa", "baby", "parents", "child",
    ]),
    ("School", [
        "teacher", "student", "class", "book", "pen",
        "pencil", "desk", "bag", "rubber", "ruler",
    ]),
    ("Friends & play", [
        "friend", "game", "fun", "laugh", "help",
        "kind", "nice", "smile", "hug", "invite",
    ]),
    ("Action verbs", [
        "sit", "stand", "run", "jump", "walk",
        "eat", "drink", "draw", "sing", "dance",
    ]),
    ("Food", [
        "food", "lunch", "dinner", "bread", "apple",
        "banana", "egg", "cake", "cheese", "pizza",
    ]),
    ("Drinks & snacks", [
        "water", "milk", "juice", "tea", "ice cream",
        "chicken", "hungry", "thirsty", "sweet", "salty",
    ]),
    ("Home", [
        "house", "room", "bedroom", "kitchen", "bathroom",
        "door", "window", "table", "chair", "bed",
    ]),
    ("Things at home", [
        "phone", "computer", "TV", "lamp", "clock",
        "key", "toy", "plant", "mirror", "sofa",
    ]),
    ("Feelings", [
        "happy", "sad", "angry", "scared", "tired",
        "bored", "surprised", "excited", "fine", "ill",
    ]),
    ("Sport & move", [
        "football", "basketball", "tennis", "swimming", "bike",
        "kick", "catch", "throw", "ride", "win",
    ]),
    ("Body", [
        "head", "face", "eye", "ear", "nose",
        "mouth", "hand", "arm", "leg", "foot",
    ]),
    ("Clothes", [
        "T-shirt", "trousers", "shorts", "jacket", "coat",
        "socks", "hat", "dress", "shoes", "wear",
    ]),
    ("Weather", [
        "sunny", "rainy", "cloudy", "windy", "snow",
        "hot", "cold", "warm", "rainbow", "umbrella",
    ]),
    ("Nature", [
        "tree", "flower", "grass", "river", "sea",
        "beach", "mountain", "forest", "park", "sky",
    ]),
    ("Animals", [
        "dog", "cat", "bird", "fish", "rabbit",
        "horse", "cow", "duck", "frog", "mouse",
    ]),
    ("City & places", [
        "city", "street", "shop", "school", "hospital",
        "zoo", "farm", "cinema", "pool", "playground",
    ]),
    ("Transport", [
        "car", "bus", "train", "plane", "bicycle",
        "boat", "taxi", "station", "ticket", "bridge",
    ]),
    ("Colours", [
        "red", "blue", "yellow", "green", "black",
        "white", "orange", "pink", "brown", "grey",
    ]),
    ("Numbers", [
        "one", "two", "three", "four", "five",
        "six", "seven", "eight", "nine", "ten",
    ]),
    ("Days & time", [
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
        "Saturday", "Sunday", "today", "tomorrow", "yesterday",
    ]),
    ("Adjectives", [
        "big", "small", "long", "short", "new",
        "old", "clean", "dirty", "fast", "slow",
    ]),
    ("More adjectives", [
        "good", "bad", "young", "tall", "quiet",
        "noisy", "left", "right", "up", "down",
    ]),
    ("Little words", [
        "yes", "no", "can", "have", "in",
        "on", "under", "next to", "between", "behind",
    ]),
    ("Everyday phrases", [
        "Come here.", "Wait a minute.", "Let's go.", "I don't know.", "I don't understand.",
        "Can you help me?", "What is this?", "Where is it?", "Are you OK?", "Thank you.",
    ]),
    ("Questions", [
        "what", "who", "where", "when", "why",
        "how", "how many", "how much", "what time", "which one",
    ]),
    ("Conversation", [
        "hello", "goodbye", "please", "thanks", "sorry",
        "excuse me", "welcome", "good morning", "good night", "see you",
    ]),
    ("Useful phrases", [
        "I like it.", "I don't like it.", "I'm hungry.", "I'm tired.", "I'm fine.",
        "It's OK.", "That's great!", "I love it.", "Me too.", "See you later.",
    ]),
    ("More verbs", [
        "open", "close", "buy", "put", "look",
        "listen", "read", "write", "cook", "tidy",
    ]),
    ("Review week", [
        "apple", "dog", "happy", "red", "mother",
        "water", "book", "car", "hello", "I like it.",
    ]),
]

# word -> (translation, pronunciation, sf_symbol, example, image_concept)
LEX: dict[str, tuple[str, str, str, str, str]] = {
    "wake up": ("просыпаться", "уэйк ап", "sunrise.fill", "I wake up at seven.", "child waking up"),
    "get up": ("вставать", "гет ап", "figure.stand", "I get up early.", "child getting out of bed"),
    "wash": ("мыть(ся)", "вош", "drop.fill", "I wash my face.", "child washing face"),
    "brush teeth": ("чистить зубы", "браш тис", "mouth.fill", "I brush my teeth.", "child brushing teeth"),
    "get dressed": ("одеваться", "гет дрест", "tshirt.fill", "I get dressed.", "child getting dressed"),
    "breakfast": ("завтрак", "брэкфаст", "cup.and.saucer.fill", "I eat breakfast.", "breakfast on table"),
    "go to school": ("идти в школу", "гоу ту скул", "building.columns.fill", "I go to school.", "child going to school"),
    "homework": ("домашнее задание", "хоумвёрк", "pencil.and.outline", "I do my homework.", "child doing homework"),
    "play": ("играть", "плэй", "gamecontroller.fill", "We play after school.", "children playing"),
    "sleep": ("спать", "слип", "bed.double.fill", "I sleep at night.", "child sleeping"),
    "family": ("семья", "фэмили", "figure.2.and.child.holdinghands", "I love my family.", "happy family"),
    "mother": ("мама", "ма́зе", "figure.stand.dress", "This is my mother.", "mother with child"),
    "father": ("папа", "фа́зе", "figure.stand", "This is my father.", "father with child"),
    "brother": ("брат", "бра́зе", "person.2.fill", "I have a brother.", "two brothers"),
    "sister": ("сестра", "си́сте", "person.2.fill", "I have a sister.", "two sisters"),
    "grandma": ("бабушка", "грэнма", "figure.stand.dress", "I visit grandma.", "grandmother"),
    "grandpa": ("дедушка", "грэнпа", "figure.stand", "I visit grandpa.", "grandfather"),
    "baby": ("малыш", "бэйби", "figure.child", "The baby is small.", "baby"),
    "parents": ("родители", "пэ́рэнтс", "person.2.fill", "My parents are kind.", "parents with child"),
    "child": ("ребёнок", "чайлд", "figure.child", "The child is happy.", "school-age child"),
    "teacher": ("учитель", "ти́чэ", "person.fill", "Our teacher is nice.", "teacher in class"),
    "student": ("ученик", "стьюдэнт", "studentdesk", "I am a student.", "student at desk"),
    "class": ("класс", "клас", "person.3.sequence", "Our class is big.", "classroom"),
    "book": ("книга", "бук", "book.fill", "I read a book.", "book"),
    "pen": ("ручка", "пен", "pencil.tip", "I write with a pen.", "pen"),
    "pencil": ("карандаш", "пэнсл", "pencil", "I need a pencil.", "pencil"),
    "desk": ("парта / стол", "деск", "table.furniture.fill", "My desk is clean.", "school desk"),
    "bag": ("сумка / портфель", "бэг", "bag.fill", "My bag is heavy.", "school bag"),
    "rubber": ("ластик", "ра́бэ", "eraser", "I use a rubber.", "eraser"),
    "ruler": ("линейка", "ру́лэ", "ruler.fill", "This is a ruler.", "ruler"),
    "friend": ("друг", "френд", "person.2.fill", "This is my friend.", "two friends"),
    "game": ("игра", "гейм", "dice.fill", "This game is fun.", "children game"),
    "fun": ("весело", "фан", "party.popper.fill", "The party is fun.", "fun party"),
    "laugh": ("смеяться", "лаф", "face.smiling.fill", "We laugh a lot.", "children laughing"),
    "help": ("помогать", "хелп", "hands.clap.fill", "Can you help me?", "child helping"),
    "kind": ("добрый", "кайнд", "heart.fill", "She is kind.", "kind child"),
    "nice": ("милый / хороший", "найс", "hand.thumbsup.fill", "He is nice.", "nice smile"),
    "smile": ("улыбка / улыбаться", "смайл", "face.smiling", "Smile, please!", "smiling child"),
    "hug": ("обнимать", "хаг", "figure.2.arms.open", "Give me a hug.", "two children hugging"),
    "invite": ("приглашать", "инвайт", "envelope.fill", "I invite my friend.", "invitation"),
    "sit": ("сидеть", "сит", "figure.seated", "Sit down, please.", "child sitting"),
    "stand": ("стоять", "стэнд", "figure.stand", "Please stand up.", "child standing"),
    "run": ("бегать", "ран", "figure.run", "I can run fast.", "child running"),
    "jump": ("прыгать", "джамп", "figure.jumprope", "I can jump.", "child jumping"),
    "walk": ("ходить пешком", "вок", "figure.walk", "We walk to school.", "child walking"),
    "eat": ("есть", "ит", "fork.knife", "I eat an apple.", "child eating"),
    "drink": ("пить", "дринк", "cup.fill", "I drink water.", "child drinking"),
    "draw": ("рисовать", "дро", "pencil.and.outline", "I draw a cat.", "child drawing"),
    "sing": ("петь", "синг", "music.mic", "We sing a song.", "child singing"),
    "dance": ("танцевать", "данс", "figure.dance", "I like to dance.", "child dancing"),
    "food": ("еда", "фуд", "fork.knife", "The food is good.", "plate of food"),
    "lunch": ("обед", "ланч", "takeoutbag.and.cup.and.straw.fill", "We eat lunch.", "lunch"),
    "dinner": ("ужин", "ди́нэ", "fork.knife.circle.fill", "Dinner is ready.", "dinner"),
    "bread": ("хлеб", "бред", "birthday.cake.fill", "I eat bread.", "bread"),
    "apple": ("яблоко", "эпл", "apple.logo", "I like apples.", "red apple"),
    "banana": ("банан", "банáна", "leaf.fill", "A yellow banana.", "banana"),
    "egg": ("яйцо", "эг", "oval.portrait.fill", "I eat an egg.", "egg"),
    "cake": ("торт / пирожное", "кейк", "birthday.cake.fill", "Happy birthday cake!", "cake"),
    "cheese": ("сыр", "чиз", "square.grid.2x2.fill", "I like cheese.", "cheese"),
    "pizza": ("пицца", "пи́тса", "circle.grid.3x3.fill", "We eat pizza.", "pizza"),
    "water": ("вода", "во́тэ", "drop.fill", "I drink water.", "glass of water"),
    "milk": ("молоко", "милк", "cup.fill", "I like milk.", "milk"),
    "juice": ("сок", "джус", "mug.fill", "Orange juice, please.", "juice"),
    "tea": ("чай", "ти", "cup.and.saucer.fill", "Mum drinks tea.", "tea"),
    "ice cream": ("мороженое", "айс крим", "cone.fill", "I love ice cream.", "ice cream"),
    "chicken": ("курица / курятина", "чи́кин", "bird.fill", "We eat chicken.", "chicken"),
    "hungry": ("голодный", "ха́нгри", "fork.knife", "I am hungry.", "hungry child"),
    "thirsty": ("хочет пить", "сёсти", "drop.circle.fill", "I am thirsty.", "thirsty child"),
    "sweet": ("сладкий", "свит", "birthday.cake.fill", "This cake is sweet.", "sweet candy"),
    "salty": ("солёный", "со́лти", "sparkles", "The soup is salty.", "salt"),
    "house": ("дом", "хаус", "house.fill", "This is my house.", "house"),
    "room": ("комната", "рум", "square.split.2x1.fill", "My room is nice.", "room"),
    "bedroom": ("спальня", "бэ́друм", "bed.double.fill", "I sleep in my bedroom.", "bedroom"),
    "kitchen": ("кухня", "ки́чн", "cooktop.fill", "Mum is in the kitchen.", "kitchen"),
    "bathroom": ("ванная", "ба́срум", "shower.fill", "I wash in the bathroom.", "bathroom"),
    "door": ("дверь", "до", "door.left.hand.open", "Open the door.", "door"),
    "window": ("окно", "уи́ндоу", "window.ceiling", "Look out the window.", "window"),
    "table": ("стол", "тэйбл", "table.furniture.fill", "The book is on the table.", "table"),
    "chair": ("стул", "чэа", "chair.fill", "Sit on the chair.", "chair"),
    "bed": ("кровать", "бед", "bed.double.fill", "I sleep in bed.", "bed"),
    "phone": ("телефон", "фоун", "iphone", "My phone is new.", "phone"),
    "computer": ("компьютер", "кэмпью́тэ", "desktopcomputer", "I use a computer.", "computer"),
    "TV": ("телевизор", "ти-ви", "tv.fill", "We watch TV.", "television"),
    "lamp": ("лампа", "лэмп", "lightbulb.fill", "Turn on the lamp.", "lamp"),
    "clock": ("часы", "клок", "clock.fill", "Look at the clock.", "clock"),
    "key": ("ключ", "ки", "key.fill", "Where is my key?", "key"),
    "toy": ("игрушка", "той", "teddybear.fill", "This toy is soft.", "toy"),
    "plant": ("растение", "плант", "leaf.fill", "A green plant.", "house plant"),
    "mirror": ("зеркало", "ми́рэ", "mirror", "Look in the mirror.", "mirror"),
    "sofa": ("диван", "со́уфа", "sofa.fill", "Sit on the sofa.", "sofa"),
    "happy": ("счастливый", "хэ́пи", "face.smiling.fill", "I am happy.", "happy child"),
    "sad": ("грустный", "сэд", "face.dashed", "She is sad.", "sad child"),
    "angry": ("сердитый", "э́нгри", "flame.fill", "Don't be angry.", "angry child"),
    "scared": ("испуганный", "скэад", "eye.trianglebadge.exclamationmark", "I am scared.", "scared child"),
    "tired": ("уставший", "та́йэд", "bed.double.fill", "I am tired.", "tired child"),
    "bored": ("скучающий", "бод", "zzz", "I am bored.", "bored child"),
    "surprised": ("удивлённый", "сэпра́йзд", "eyes", "I am surprised!", "surprised child"),
    "excited": ("взволнованный", "икса́йтид", "star.fill", "I am excited!", "excited child"),
    "fine": ("в порядке", "файн", "checkmark.circle.fill", "I am fine.", "OK child"),
    "ill": ("больной", "ил", "cross.case.fill", "I am ill today.", "ill child"),
    "football": ("футбол", "футбол", "soccerball", "We play football.", "football"),
    "basketball": ("баскетбол", "ба́скетбол", "basketball.fill", "I like basketball.", "basketball"),
    "tennis": ("теннис", "тэнис", "tennisball.fill", "She plays tennis.", "tennis"),
    "swimming": ("плавание", "суи́минг", "figure.pool.swim", "Swimming is fun.", "swimming"),
    "bike": ("велосипед", "байк", "bicycle", "I ride a bike.", "bike"),
    "kick": ("пинать", "кик", "figure.soccer", "Kick the ball.", "kicking ball"),
    "catch": ("ловить", "кэч", "hand.raised.fill", "Catch the ball!", "catching ball"),
    "throw": ("бросать", "сроу", "figure.boxing", "Throw the ball.", "throwing ball"),
    "ride": ("ездить верхом / кататься", "райд", "bicycle", "I ride my bike.", "riding bike"),
    "win": ("побеждать", "вин", "trophy.fill", "We want to win.", "trophy"),
    "head": ("голова", "хед", "brain.head.profile", "My head hurts.", "head"),
    "face": ("лицо", "фэйс", "face.smiling", "Wash your face.", "face"),
    "eye": ("глаз", "ай", "eye.fill", "I have brown eyes.", "eye"),
    "ear": ("ухо", "иэ", "ear.fill", "Listen with your ears.", "ear"),
    "nose": ("нос", "ноуз", "nose.fill", "My nose is cold.", "nose"),
    "mouth": ("рот", "маус", "mouth.fill", "Open your mouth.", "mouth"),
    "hand": ("рука (кисть)", "хэнд", "hand.raised.fill", "Raise your hand.", "hand"),
    "arm": ("рука (от плеча)", "ам", "hand.raised.fill", "My arm is long.", "arm"),
    "leg": ("нога", "лег", "figure.walk", "My leg is strong.", "leg"),
    "foot": ("ступня", "фут", "shoe.fill", "My foot is small.", "foot"),
    "T-shirt": ("футболка", "ти-шёт", "tshirt.fill", "I wear a T-shirt.", "T-shirt"),
    "trousers": ("брюки", "тра́узез", "pants.fill", "These trousers are new.", "trousers"),
    "shorts": ("шорты", "шотс", "pants.fill", "I wear shorts.", "shorts"),
    "jacket": ("куртка", "джэ́кит", "jacket.fill", "Put on your jacket.", "jacket"),
    "coat": ("пальто", "коут", "jacket.fill", "My coat is warm.", "coat"),
    "socks": ("носки", "сокс", "sock.fill", "I need clean socks.", "socks"),
    "hat": ("шапка / шляпа", "хэт", "crown.fill", "This hat is warm.", "hat"),
    "dress": ("платье", "дрес", "figure.stand.dress", "She wears a dress.", "dress"),
    "shoes": ("обувь", "шуз", "shoe.fill", "Put on your shoes.", "shoes"),
    "wear": ("носить (одежду)", "вэа", "tshirt.fill", "I wear shoes.", "wearing clothes"),
    "sunny": ("солнечно", "са́ни", "sun.max.fill", "It is sunny.", "sunny day"),
    "rainy": ("дождливо", "рэ́йни", "cloud.rain.fill", "It is rainy.", "rainy day"),
    "cloudy": ("облачно", "кла́уди", "cloud.fill", "It is cloudy.", "cloudy sky"),
    "windy": ("ветрено", "уи́нди", "wind", "It is windy.", "windy day"),
    "snow": ("снег", "сноу", "snowflake", "I like snow.", "snow"),
    "hot": ("горячий / жаркий", "хот", "thermometer.sun.fill", "It is hot.", "hot sun"),
    "cold": ("холодный", "коулд", "thermometer.snowflake", "It is cold.", "cold weather"),
    "warm": ("тёплый", "вом", "sun.min.fill", "It is warm today.", "warm day"),
    "rainbow": ("радуга", "рэ́йнбоу", "rainbow", "Look at the rainbow!", "rainbow"),
    "umbrella": ("зонт", "амбрэ́ла", "umbrella.fill", "Take an umbrella.", "umbrella"),
    "tree": ("дерево", "три", "tree.fill", "The tree is tall.", "tree"),
    "flower": ("цветок", "фла́уэ", "camera.macro", "This flower is red.", "flower"),
    "grass": ("трава", "грас", "leaf.fill", "The grass is green.", "grass"),
    "river": ("река", "ри́вэ", "water.waves", "We sit by the river.", "river"),
    "sea": ("море", "си", "water.waves", "The sea is big.", "sea"),
    "beach": ("пляж", "бич", "beach.umbrella.fill", "We play on the beach.", "beach"),
    "mountain": ("гора", "ма́унтин", "mountain.2.fill", "The mountain is high.", "mountain"),
    "forest": ("лес", "фо́рист", "tree.fill", "Animals live in the forest.", "forest"),
    "park": ("парк", "пак", "tree.fill", "We play in the park.", "park"),
    "sky": ("небо", "скай", "cloud.fill", "The sky is blue.", "sky"),
    "dog": ("собака", "дог", "dog.fill", "The dog is friendly.", "dog"),
    "cat": ("кошка", "кэт", "cat.fill", "The cat sleeps.", "cat"),
    "bird": ("птица", "бёд", "bird.fill", "The bird can fly.", "bird"),
    "fish": ("рыба", "фиш", "fish.fill", "The fish is orange.", "fish"),
    "rabbit": ("кролик", "рэ́бит", "hare.fill", "The rabbit is white.", "rabbit"),
    "horse": ("лошадь", "хорс", "hare.fill", "The horse is fast.", "horse"),
    "cow": ("корова", "кау", "hare.fill", "The cow eats grass.", "cow"),
    "duck": ("утка", "дак", "bird.fill", "The duck swims.", "duck"),
    "frog": ("лягушка", "фрог", "lizard.fill", "The frog is green.", "frog"),
    "mouse": ("мышь", "маус", "hare.fill", "A small mouse.", "mouse"),
    "city": ("город", "си́ти", "building.2.fill", "I live in a city.", "city"),
    "street": ("улица", "стрит", "road.lanes", "This street is quiet.", "street"),
    "shop": ("магазин", "шоп", "storefront.fill", "I buy bread in the shop.", "shop"),
    "school": ("школа", "скул", "building.columns.fill", "I go to school.", "school"),
    "hospital": ("больница", "хо́спитл", "cross.case.fill", "The hospital is near.", "hospital"),
    "zoo": ("зоопарк", "зу", "pawprint.fill", "We go to the zoo.", "zoo"),
    "farm": ("ферма", "фам", "leaf.fill", "Animals live on a farm.", "farm"),
    "cinema": ("кинотеатр", "си́нема", "film.fill", "We go to the cinema.", "cinema"),
    "pool": ("бассейн", "пул", "figure.pool.swim", "I swim in the pool.", "swimming pool"),
    "playground": ("детская площадка", "плэ́йграунд", "figure.play", "We run in the playground.", "playground"),
    "car": ("машина", "ка", "car.fill", "Dad drives a car.", "car"),
    "bus": ("автобус", "бас", "bus.fill", "I go by bus.", "bus"),
    "train": ("поезд", "трэйн", "tram.fill", "The train is fast.", "train"),
    "plane": ("самолёт", "плэйн", "airplane", "The plane flies.", "plane"),
    "bicycle": ("велосипед", "ба́йсикл", "bicycle", "I ride a bicycle.", "bicycle"),
    "boat": ("лодка / корабль", "боут", "ferry.fill", "We are on a boat.", "boat"),
    "taxi": ("такси", "тэ́кси", "car.fill", "We take a taxi.", "taxi"),
    "station": ("станция / вокзал", "стэйшн", "tram.fill", "Wait at the station.", "station"),
    "ticket": ("билет", "ти́кит", "ticket.fill", "I have a ticket.", "ticket"),
    "bridge": ("мост", "бридж", "road.lanes", "Look at the bridge.", "bridge"),
    "red": ("красный", "ред", "circle.fill", "A red apple.", "red colour"),
    "blue": ("синий", "блу", "circle.fill", "A blue sky.", "blue colour"),
    "yellow": ("жёлтый", "йе́лоу", "circle.fill", "A yellow banana.", "yellow colour"),
    "green": ("зелёный", "грин", "circle.fill", "Green grass.", "green colour"),
    "black": ("чёрный", "блэк", "circle.fill", "A black cat.", "black colour"),
    "white": ("белый", "уайт", "circle.fill", "A white rabbit.", "white colour"),
    "orange": ("оранжевый", "о́риндж", "circle.fill", "An orange ball.", "orange colour"),
    "pink": ("розовый", "пинк", "circle.fill", "A pink hat.", "pink colour"),
    "brown": ("коричневый", "браун", "circle.fill", "Brown eyes.", "brown colour"),
    "grey": ("серый", "грей", "circle.fill", "A grey cloud.", "grey colour"),
    "one": ("один", "уан", "1.circle.fill", "I have one book.", "number 1"),
    "two": ("два", "ту", "2.circle.fill", "I have two cats.", "number 2"),
    "three": ("три", "сри", "3.circle.fill", "I see three birds.", "number 3"),
    "four": ("четыре", "фо", "4.circle.fill", "Four chairs.", "number 4"),
    "five": ("пять", "файв", "5.circle.fill", "Five fingers.", "number 5"),
    "six": ("шесть", "сикс", "6.circle.fill", "Six eggs.", "number 6"),
    "seven": ("семь", "сэвн", "7.circle.fill", "Seven days.", "number 7"),
    "eight": ("восемь", "эйт", "8.circle.fill", "Eight apples.", "number 8"),
    "nine": ("девять", "найн", "9.circle.fill", "Nine books.", "number 9"),
    "ten": ("десять", "тен", "10.circle.fill", "Ten toes.", "number 10"),
    "Monday": ("понедельник", "ма́ндей", "calendar", "Today is Monday.", "Monday"),
    "Tuesday": ("вторник", "тью́здей", "calendar", "Today is Tuesday.", "Tuesday"),
    "Wednesday": ("среда", "уэ́нздей", "calendar", "Today is Wednesday.", "Wednesday"),
    "Thursday": ("четверг", "сё́здей", "calendar", "Today is Thursday.", "Thursday"),
    "Friday": ("пятница", "фра́йдей", "calendar", "Today is Friday.", "Friday"),
    "Saturday": ("суббота", "сэ́тедей", "calendar", "Today is Saturday.", "Saturday"),
    "Sunday": ("воскресенье", "са́ндей", "calendar", "Today is Sunday.", "Sunday"),
    "today": ("сегодня", "тудэй", "calendar", "Today is fun.", "today"),
    "tomorrow": ("завтра", "тумо́роу", "calendar.badge.plus", "See you tomorrow.", "tomorrow"),
    "yesterday": ("вчера", "йе́стэдэй", "calendar.badge.minus", "Yesterday was nice.", "yesterday"),
    "big": ("большой", "биг", "arrow.up.left.and.arrow.down.right", "A big dog.", "big object"),
    "small": ("маленький", "смол", "arrow.down.right.and.arrow.up.left", "A small cat.", "small object"),
    "long": ("длинный", "лонг", "ruler.fill", "Long hair.", "long object"),
    "short": ("короткий", "шот", "ruler", "Short hair.", "short object"),
    "new": ("новый", "нью", "sparkles", "A new bag.", "new item"),
    "old": ("старый", "оулд", "clock.fill", "An old book.", "old item"),
    "clean": ("чистый", "клин", "sparkles", "My room is clean.", "clean room"),
    "dirty": ("грязный", "дёти", "trash.fill", "My shoes are dirty.", "dirty shoes"),
    "fast": ("быстрый", "фаст", "hare.fill", "A fast car.", "fast car"),
    "slow": ("медленный", "слоу", "tortoise.fill", "A slow turtle.", "slow animal"),
    "good": ("хороший", "гуд", "hand.thumbsup.fill", "Good job!", "thumbs up"),
    "bad": ("плохой", "бэд", "hand.thumbsdown.fill", "Bad idea.", "thumbs down"),
    "young": ("молодой", "янг", "figure.child", "A young child.", "young person"),
    "tall": ("высокий", "тол", "arrow.up", "A tall tree.", "tall person"),
    "quiet": ("тихий", "куа́йет", "speaker.slash.fill", "Please be quiet.", "quiet"),
    "noisy": ("шумный", "но́йзи", "speaker.wave.3.fill", "The street is noisy.", "noisy"),
    "left": ("левый / налево", "лефт", "arrow.left", "Turn left.", "left arrow"),
    "right": ("правый / направо", "райт", "arrow.right", "Turn right.", "right arrow"),
    "up": ("вверх", "ап", "arrow.up", "Look up!", "up arrow"),
    "down": ("вниз", "даун", "arrow.down", "Sit down.", "down arrow"),
    "yes": ("да", "йес", "checkmark.circle.fill", "Yes, please.", "yes"),
    "no": ("нет", "ноу", "xmark.circle.fill", "No, thanks.", "no"),
    "can": ("мочь / уметь", "кэн", "hand.raised.fill", "I can swim.", "can do"),
    "have": ("иметь", "хэв", "gift.fill", "I have a dog.", "have"),
    "in": ("в", "ин", "square.filled.on.square", "The book is in the bag.", "in"),
    "on": ("на", "он", "square.on.square", "The book is on the table.", "on"),
    "under": ("под", "а́ндэ", "rectangle.bottomhalf.filled", "Under the table.", "under"),
    "next to": ("рядом с", "некст ту", "rectangle.split.2x1", "Next to the door.", "next to"),
    "between": ("между", "битуи́н", "rectangle.split.3x1", "Between two chairs.", "between"),
    "behind": ("за", "биха́йнд", "rectangle.portrait.bottomthird.inset.filled", "Behind the door.", "behind"),
    "Come here.": ("Иди сюда.", "кам хиэ", "hand.wave.fill", "Come here, please.", "come here"),
    "Wait a minute.": ("Подожди минуту.", "уэйт э ми́нит", "clock.fill", "Wait a minute.", "waiting"),
    "Let's go.": ("Пойдём.", "летс гоу", "figure.walk", "Let's go home.", "let's go"),
    "I don't know.": ("Я не знаю.", "ай доунт ноу", "questionmark.circle", "I don't know.", "I don't know"),
    "I don't understand.": ("Я не понимаю.", "ай доунт андэстэнд", "ear", "I don't understand.", "confused"),
    "Can you help me?": ("Можешь помочь?", "кэн ю хелп ми", "hands.clap.fill", "Can you help me?", "asking help"),
    "What is this?": ("Что это?", "вот из зис", "questionmark.circle.fill", "What is this?", "what is this"),
    "Where is it?": ("Где это?", "вэа из ит", "mappin.circle.fill", "Where is it?", "where"),
    "Are you OK?": ("Ты в порядке?", "а ю оу-кей", "heart.circle.fill", "Are you OK?", "are you ok"),
    "Thank you.": ("Спасибо.", "сэнк ю", "hands.clap.fill", "Thank you!", "thank you"),
    "what": ("что / какой", "вот", "questionmark.circle.fill", "What is your name?", "what"),
    "who": ("кто", "ху", "person.crop.circle.badge.questionmark", "Who is that?", "who"),
    "where": ("где", "вэа", "mappin.and.ellipse", "Where do you live?", "where"),
    "when": ("когда", "уэн", "calendar.circle.fill", "When is the lesson?", "when"),
    "why": ("почему", "уай", "questionmark.bubble.fill", "Why are you sad?", "why"),
    "how": ("как", "хау", "gearshape.fill", "How are you?", "how"),
    "how many": ("сколько (штук)", "хау мэни", "number.circle.fill", "How many books?", "how many"),
    "how much": ("сколько (цены/неисч.)", "хау мач", "yensign.circle.fill", "How much is it?", "how much"),
    "what time": ("который час", "вот тайм", "clock.fill", "What time is it?", "what time"),
    "which one": ("который / какой из", "уич уан", "checklist", "Which one do you want?", "which one"),
    "hello": ("привет", "хелóу", "hand.wave.fill", "Hello!", "hello"),
    "goodbye": ("до свидания", "гудба́й", "hand.wave", "Goodbye!", "goodbye"),
    "please": ("пожалуйста", "плиз", "heart.fill", "Help me, please.", "please"),
    "thanks": ("спасибо", "сэнкс", "hands.clap.fill", "Thanks a lot!", "thanks"),
    "sorry": ("извини", "со́ри", "face.dashed", "I am sorry.", "sorry"),
    "excuse me": ("извините", "икскьюз ми", "hand.raised.fill", "Excuse me!", "excuse me"),
    "welcome": ("добро пожаловать", "уэлкам", "house.fill", "Welcome!", "welcome"),
    "good morning": ("доброе утро", "гуд мо́нинг", "sunrise.fill", "Good morning!", "good morning"),
    "good night": ("спокойной ночи", "гуд найт", "moon.stars.fill", "Good night!", "good night"),
    "see you": ("увидимся", "си ю", "hand.wave", "See you!", "see you"),
    "I like it.": ("Мне нравится.", "ай лайк ит", "hand.thumbsup.fill", "I like it.", "I like it"),
    "I don't like it.": ("Мне не нравится.", "ай доунт лайк ит", "hand.thumbsdown.fill", "I don't like it.", "dislike"),
    "I'm hungry.": ("Я голодный.", "айм ха́нгри", "fork.knife", "I'm hungry.", "hungry"),
    "I'm tired.": ("Я устал.", "айм та́йэд", "bed.double.fill", "I'm tired.", "tired"),
    "I'm fine.": ("У меня всё хорошо.", "айм файн", "checkmark.circle.fill", "I'm fine.", "I'm fine"),
    "It's OK.": ("Всё нормально.", "итс оу-кей", "checkmark.circle", "It's OK.", "OK"),
    "That's great!": ("Отлично!", "зэтс грейт", "star.fill", "That's great!", "great"),
    "I love it.": ("Я обожаю это.", "ай лав ит", "heart.fill", "I love it!", "love it"),
    "Me too.": ("Я тоже.", "ми ту", "person.2.fill", "Me too!", "me too"),
    "See you later.": ("Увидимся позже.", "си ю лэ́йтэ", "hand.wave", "See you later!", "see you later"),
    "open": ("открывать", "о́упэн", "door.left.hand.open", "Open the window.", "open"),
    "close": ("закрывать", "клоуз", "door.left.hand.closed", "Close the door.", "close"),
    "buy": ("покупать", "бай", "cart.fill", "I buy milk.", "buy"),
    "put": ("класть / ставить", "пут", "square.and.arrow.down.fill", "Put it here.", "put"),
    "look": ("смотреть", "лук", "eye.fill", "Look at me!", "look"),
    "listen": ("слушать", "ли́сн", "ear.fill", "Listen to me.", "listen"),
    "read": ("читать", "рид", "book.fill", "I read every day.", "read"),
    "write": ("писать", "райт", "pencil", "Write your name.", "write"),
    "cook": ("готовить", "кук", "frying.pan.fill", "Mum can cook.", "cook"),
    "tidy": ("убирать / приводить в порядок", "та́йди", "sparkles", "Tidy your room.", "tidying room"),
}

# Ensure adjective "clean" stays in LEX (day 22); verb day uses "tidy".

# For review day, "clean" as verb in day 29 vs adjective day 22 - same word OK for kids
# But LEX has one entry - day 29 uses "clean" as verb sense in example - fine

FLUENT: dict[str, str] = {
    "wake up": "Alarm clock", "wash": "Soap", "get dressed": "T-shirt", "breakfast": "Cooking",
    "homework": "Memo", "play": "Jigsaw", "sleep": "Sleeping face", "family": "Family",
    "baby": "Baby", "teacher": "Teacher", "student": "Student", "book": "Closed book",
    "pen": "Pen", "pencil": "Pencil", "bag": "Backpack", "friend": "People hugging",
    "game": "Video game", "fun": "Party popper", "laugh": "Face with tears of joy",
    "smile": "Slightly smiling face", "hug": "People hugging", "sit": "Chair",
    "run": "Person running", "walk": "Person walking", "eat": "Fork and knife",
    "drink": "Cup with straw", "draw": "Crayon", "sing": "Microphone", "dance": "Woman dancing",
    "food": "Fork and knife with plate", "lunch": "Sandwich", "dinner": "Pot of food",
    "bread": "Bread", "apple": "Red apple", "banana": "Banana", "egg": "Egg",
    "cake": "Shortcake", "cheese": "Cheese wedge", "pizza": "Pizza", "water": "Water wave",
    "milk": "Glass of milk", "juice": "Beverage box", "tea": "Teacup without handle",
    "ice cream": "Soft ice cream", "chicken": "Cooked chicken", "hungry": "Fork and knife",
    "thirsty": "Potable water", "sweet": "Shortcake", "salty": "Salt", "house": "House",
    "bedroom": "Bed", "bathroom": "Toilet", "door": "Door", "window": "Window",
    "chair": "Chair", "bed": "Bed", "phone": "Mobile phone", "computer": "Laptop",
    "TV": "Television", "lamp": "Light bulb", "clock": "Alarm clock", "key": "Key",
    "toy": "Teddy bear", "plant": "Potted plant", "mirror": "Mirror", "sofa": "Couch and lamp",
    "happy": "Grinning face", "sad": "Crying face", "angry": "Angry face",
    "scared": "Fearful face", "tired": "Sleepy face", "bored": "Sleeping face",
    "surprised": "Astonished face", "excited": "Star-struck", "fine": "OK hand",
    "ill": "Face with thermometer", "football": "Soccer ball", "basketball": "Basketball",
    "tennis": "Tennis", "bike": "Bicycle", "win": "Trophy", "head": "Bust in silhouette",
    "face": "Slightly smiling face", "eye": "Eye", "mouth": "Mouth", "T-shirt": "T-shirt",
    "trousers": "Jeans", "shorts": "Shorts", "jacket": "Coat", "coat": "Coat",
    "socks": "Socks", "hat": "Top hat", "dress": "Dress", "shoes": "Running shoe",
    "wear": "T-shirt", "sunny": "Sun", "rainy": "Cloud with rain", "cloudy": "Cloud",
    "windy": "Leaf fluttering in wind", "snow": "Snowflake", "hot": "Hot beverage",
    "cold": "Cold face", "warm": "Sun", "rainbow": "Rainbow", "umbrella": "Umbrella",
    "tree": "Deciduous tree", "flower": "Sunflower", "grass": "Seedling", "river": "Water wave",
    "sea": "Water wave", "beach": "Beach with umbrella", "mountain": "Mountain",
    "forest": "National park", "park": "National park", "sky": "Sun behind large cloud",
    "dog": "Dog", "cat": "Cat", "bird": "Bird", "fish": "Fish", "rabbit": "Rabbit",
    "horse": "Horse", "cow": "Cow", "duck": "Duck", "frog": "Frog", "mouse": "Mouse",
    "city": "Cityscape", "street": "Motorway", "shop": "Department store", "school": "School",
    "hospital": "Hospital", "zoo": "Lion", "farm": "Sheaf of rice", "cinema": "Movie camera",
    "car": "Automobile", "bus": "Bus", "train": "Train", "plane": "Airplane",
    "bicycle": "Bicycle", "boat": "Sailboat", "taxi": "Oncoming taxi", "station": "Station",
    "ticket": "Ticket", "bridge": "Bridge at night", "red": "Red circle", "blue": "Blue circle",
    "yellow": "Yellow circle", "green": "Green circle", "black": "Black circle",
    "white": "White circle", "orange": "Orange circle", "brown": "Brown circle",
    "one": "Keycap 1", "two": "Keycap 2", "three": "Keycap 3", "four": "Keycap 4",
    "five": "Keycap 5", "six": "Keycap 6", "seven": "Keycap 7", "eight": "Keycap 8",
    "nine": "Keycap 9", "ten": "Keycap 10", "today": "Calendar", "tomorrow": "Tear-off calendar",
    "yesterday": "Calendar", "big": "Elephant", "small": "Mouse", "long": "Straight ruler",
    "short": "Straight ruler", "new": "Sparkles", "clean": "Soap", "fast": "Rabbit",
    "slow": "Turtle", "young": "Child", "yes": "Check mark button", "no": "Cross mark",
    "can": "OK hand", "have": "Wrapped gift", "open": "Open file folder", "close": "Locked",
    "buy": "Shopping cart", "put": "Inbox tray", "look": "Eye", "listen": "Ear",
    "read": "Open book", "write": "Memo", "cook": "Cook", "tidy": "Soap",
    "Wait a minute.": "Hourglass not done", "I don't understand.": "Thinking face",
    "What is this?": "Red question mark", "Where is it?": "Round pushpin",
    "what": "Red question mark", "who": "Bust in silhouette", "where": "Round pushpin",
    "when": "Alarm clock", "why": "Red question mark", "how": "Red question mark",
    "how many": "Input numbers", "how much": "Money bag", "hello": "Waving hand",
    "sorry": "Pensive face", "welcome": "House with garden", "good morning": "Sunrise",
    "good night": "Night with stars", "I like it.": "Thumbs up", "I don't like it.": "Thumbs down",
    "I'm hungry.": "Fork and knife", "I'm tired.": "Sleepy face", "I'm fine.": "OK hand",
    "That's great!": "Star-struck", "I love it.": "Red heart",
}

EMOJI: dict[str, str] = {
    "wake up": "⏰", "get up": "🛏️", "wash": "🧼", "brush teeth": "🦷", "get dressed": "👕",
    "breakfast": "🍳", "go to school": "🏫", "homework": "📝", "play": "🎮", "sleep": "😴",
    "family": "👨‍👩‍👧‍👦", "mother": "👩", "father": "👨", "brother": "👦", "sister": "👧",
    "grandma": "👵", "grandpa": "👴", "baby": "👶", "parents": "👨‍👩‍👧", "child": "🧒",
    "teacher": "👩‍🏫", "student": "🧑‍🎓", "class": "🏫", "book": "📖", "pen": "🖊️",
    "pencil": "✏️", "desk": "🪑", "bag": "🎒", "rubber": "🧽", "ruler": "📏",
    "friend": "👫", "game": "🎲", "fun": "🎉", "laugh": "😂", "help": "🆘",
    "kind": "💗", "nice": "😊", "smile": "😄", "hug": "🤗", "invite": "📨",
    "sit": "🪑", "stand": "🧍", "run": "🏃", "jump": "🦘", "walk": "🚶",
    "eat": "🍽️", "drink": "🥤", "draw": "🎨", "sing": "🎤", "dance": "💃",
    "food": "🍽️", "lunch": "🥪", "dinner": "🍲", "bread": "🍞", "apple": "🍎",
    "banana": "🍌", "egg": "🥚", "cake": "🎂", "cheese": "🧀", "pizza": "🍕",
    "water": "💧", "milk": "🥛", "juice": "🧃", "tea": "🍵", "ice cream": "🍦",
    "chicken": "🍗", "hungry": "😋", "thirsty": "🥤", "sweet": "🍬", "salty": "🧂",
    "house": "🏠", "room": "🚪", "bedroom": "🛏️", "kitchen": "👩‍🍳", "bathroom": "🚽",
    "door": "🚪", "window": "🪟", "table": "🪑", "chair": "🪑", "bed": "🛏️",
    "phone": "📱", "computer": "💻", "TV": "📺", "lamp": "💡", "clock": "⏰",
    "key": "🔑", "toy": "🧸", "plant": "🪴", "mirror": "🪞", "sofa": "🛋️",
    "happy": "😄", "sad": "😢", "angry": "😠", "scared": "😨", "tired": "😴",
    "bored": "😑", "surprised": "😲", "excited": "🤩", "fine": "👌", "ill": "🤒",
    "football": "⚽", "basketball": "🏀", "tennis": "🎾", "swimming": "🏊", "bike": "🚲",
    "kick": "⚽", "catch": "キャッチ", "throw": "⚾", "ride": "🚴", "win": "🏆",
    "head": "🙂", "face": "😊", "eye": "👁️", "ear": "👂", "nose": "👃",
    "mouth": "👄", "hand": "✋", "arm": "💪", "leg": "🦵", "foot": "🦶",
    "T-shirt": "👕", "trousers": "👖", "shorts": "🩳", "jacket": "🧥", "coat": "🧥",
    "socks": "🧦", "hat": "🎩", "dress": "👗", "shoes": "👟", "wear": "👕",
    "sunny": "☀️", "rainy": "🌧️", "cloudy": "☁️", "windy": "💨", "snow": "❄️",
    "hot": "🥵", "cold": "🥶", "warm": "🌞", "rainbow": "🌈", "umbrella": "☂️",
    "tree": "🌳", "flower": "🌻", "grass": "🌱", "river": "🏞️", "sea": "🌊",
    "beach": "🏖️", "mountain": "⛰️", "forest": "🌲", "park": "🏞️", "sky": "🌌",
    "dog": "🐶", "cat": "🐱", "bird": "🐦", "fish": "🐟", "rabbit": "🐰",
    "horse": "🐴", "cow": "🐮", "duck": "🦆", "frog": "🐸", "mouse": "🐭",
    "city": "🏙️", "street": "🛣️", "shop": "🛍️", "school": "🏫", "hospital": "🏥",
    "zoo": "🦁", "farm": "🌾", "cinema": "🎬", "pool": "🏊", "playground": "🛝",
    "car": "🚗", "bus": "🚌", "train": "🚆", "plane": "✈️", "bicycle": "🚲",
    "boat": "⛵", "taxi": "🚕", "station": "🚉", "ticket": "🎫", "bridge": "🌉",
    "red": "🔴", "blue": "🔵", "yellow": "🟡", "green": "🟢", "black": "⚫",
    "white": "⚪", "orange": "🟠", "pink": "💗", "brown": "🟤", "grey": "⚙️",
    "one": "1️⃣", "two": "2️⃣", "three": "3️⃣", "four": "4️⃣", "five": "5️⃣",
    "six": "6️⃣", "seven": "7️⃣", "eight": "8️⃣", "nine": "9️⃣", "ten": "🔟",
    "Monday": "📅", "Tuesday": "📅", "Wednesday": "📅", "Thursday": "📅", "Friday": "📅",
    "Saturday": "📅", "Sunday": "📅", "today": "📅", "tomorrow": "📆", "yesterday": "🗓️",
    "big": "🐘", "small": "🐭", "long": "📏", "short": "📐", "new": "🆕",
    "old": "🧓", "clean": "✨", "dirty": "🧽", "fast": "🐇", "slow": "🐢",
    "good": "👍", "bad": "👎", "young": "🧒", "tall": "📏", "quiet": "🤫",
    "noisy": "🔊", "left": "⬅️", "right": "➡️", "up": "⬆️", "down": "⬇️",
    "yes": "✅", "no": "❌", "can": "👍", "have": "🎁", "in": "📥",
    "on": "📌", "under": "⬇️", "next to": "↔️", "between": "🔀", "behind": "🔙",
    "Come here.": "👈", "Wait a minute.": "⏳", "Let's go.": "🏃", "I don't know.": "🤷",
    "I don't understand.": "🤔", "Can you help me?": "🙋", "What is this?": "❓",
    "Where is it?": "📍", "Are you OK?": "👌", "Thank you.": "🙏",
    "what": "❓", "who": "👤", "where": "📍", "when": "⏰", "why": "❓",
    "how": "❓", "how many": "🔢", "how much": "💰", "what time": "🕐", "which one": "🔢",
    "hello": "👋", "goodbye": "👋", "please": "🙏", "thanks": "🙏", "sorry": "😔",
    "excuse me": "🙋", "welcome": "🏡", "good morning": "🌅", "good night": "🌙", "see you": "👋",
    "I like it.": "👍", "I don't like it.": "👎", "I'm hungry.": "🍽️", "I'm tired.": "😴",
    "I'm fine.": "😊", "It's OK.": "👌", "That's great!": "🤩", "I love it.": "❤️",
    "Me too.": "🤝", "See you later.": "👋", "open": "📂", "close": "🔒", "buy": "🛒",
    "put": "📥", "look": "👀", "listen": "👂", "read": "📖", "write": "✍️",
    "cook": "🍳", "tidy": "🧹",
}

# fix bad emoji
EMOJI["catch"] = "🥎"
EMOJI["grey"] = "⚪"


def main() -> None:
    assert len(DAYS) == 30
    words_out = []
    csv_rows = []
    missing_lex = []
    seen_new = []
    for day_i, (theme, words) in enumerate(DAYS, start=1):
        assert len(words) == 10, (day_i, len(words), words)
        for w in words:
            if w not in LEX:
                missing_lex.append(w)
            seen_new.append(w)

    if missing_lex:
        raise SystemExit(f"Missing LEX: {missing_lex}")

    # uniqueness except review day 30
    non_review = []
    for day_i, (_, words) in enumerate(DAYS, start=1):
        if day_i < 30:
            non_review.extend(words)
    dup_early = [w for w, n in __import__("collections").Counter(non_review).items() if n > 1]
    if dup_early:
        raise SystemExit(f"Unexpected duplicates before review day: {dup_early}")

    wid = 1
    for day_i, (theme, words) in enumerate(DAYS, start=1):
        for w in words:
            tr, pr, sym, ex, concept = LEX[w]
            asset = f"word_{wid:03d}"
            words_out.append({
                "id": wid,
                "asset_id": asset,
                "day": day_i,
                "theme": theme,
                "word": w,
                "pronunciation": pr,
                "translation": tr,
                "example": ex,
                "image_concept": concept,
                "visual": {
                    "mode": "sf_symbol",
                    "sf_symbol": sym,
                    "image_file": None,
                    "wikivoc_file": None,
                    "image_source": None,
                    "image_detail": None,
                },
                "fluent_hint": FLUENT.get(w),
                "emoji_hint": EMOJI.get(w),
                "is_review": day_i == 30,
            })
            csv_rows.append({
                "id": wid,
                "day": day_i,
                "theme": theme,
                "word": w,
                "image_concept": concept,
                "style": "clean colorful educational illustration; age 10; one clear subject; simple background; no text",
                "image_search_query": f"{concept}, children's English vocabulary flashcard",
            })
            wid += 1

    payload = {
        "version": 2,
        "title": "English Word Widget Kids",
        "locale_hint": "ru-child",
        "count": len(words_out),
        "days": 30,
        "words_per_day": 10,
        "visual_strategy": "fluent_3d_then_twemoji_then_sf_symbol",
        "curriculum_notes": "v2: fewer duplicates, more Starters basics, day 30 = review",
        "attribution": {
            "fluent_ui_emoji": {
                "source": "https://github.com/microsoft/fluentui-emoji",
                "license": "MIT",
                "credit": "Fluent Emoji by Microsoft (MIT)",
            },
            "twemoji": {
                "source": "https://github.com/jdecked/twemoji",
                "license": "CC-BY 4.0 (graphics), MIT (code)",
                "credit": "Twemoji graphics © Twitter/jdecked, CC-BY 4.0",
            },
        },
        "words": [{k: v for k, v in item.items() if k not in ("fluent_hint", "emoji_hint")} for item in words_out],
    }

    # stash hints for fetch script
    hints = {item["word"]: {"fluent": item.get("fluent_hint"), "emoji": item.get("emoji_hint")} for item in words_out}
    (ROOT / "data" / "image_hints_v2.json").write_text(json.dumps(hints, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    WORDS_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    APP_WORDS.parent.mkdir(parents=True, exist_ok=True)
    APP_WORDS.write_text(WORDS_PATH.read_text(encoding="utf-8"), encoding="utf-8")

    with CSV_PATH.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "day", "theme", "word", "image_concept", "style", "image_search_query"])
        writer.writeheader()
        writer.writerows(csv_rows)

    unique = len(set(non_review))
    NOTES.write_text(
        "\n".join([
            "# Curriculum v2",
            "",
            "- 30 days × 10 slots = 300 cards",
            f"- Unique new words (days 1–29): **{unique}**",
            "- Day 30: review of 10 key words (intentional repeats)",
            "- Added: colours, numbers 1–10, days of week, grandma/grandpa/baby, zoo/farm, snow, prepositions, yes/no/can/have",
            "- Removed/deferred: abstract core day, passport/motorbike-heavy travel, early whose/which/subject/idea",
            "",
            "Rebuild images: `python3 scripts/fetch_word_images.py`",
            "",
        ]),
        encoding="utf-8",
    )
    print(f"Wrote {WORDS_PATH} ({len(words_out)} cards, {unique} unique before review)")
    print(f"Wrote {CSV_PATH}")
    print(f"Wrote {NOTES}")


if __name__ == "__main__":
    main()
